apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: web
        image: library_management_system:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: app-configmap
          - secretRef:
              name: app-secret
        readinessProbe:
          httpGet:
            path: /library/health/
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /library/health/
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
