# Generated by Django 5.2.3 on 2025-06-21 21:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "genre_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                ("member_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("password", models.TextField(max_length=255)),
                ("membership_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publishers",
            fields=[
                (
                    "publisher_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("publisher_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Authors",
            fields=[
                ("author_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["first_name", "last_name"], name="author_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "isbn",
                    models.CharField(max_length=17, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "publication_year",
                    models.IntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1970)],
                    ),
                ),
                ("language", models.CharField(max_length=3)),
                (
                    "total_quantity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99),
                        ]
                    ),
                ),
                ("authors", models.ManyToManyField(to="library_manager.authors")),
                ("genres", models.ManyToManyField(to="library_manager.genres")),
                ("publishers", models.ManyToManyField(to="library_manager.publishers")),
            ],
        ),
        migrations.CreateModel(
            name="Loans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "isbn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_manager.books",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="library_manager.members",
                    ),
                ),
            ],
            options={
                "unique_together": {("member_id", "isbn")},
            },
        ),
    ]
