# Generated by Django 5.2.3 on 2025-06-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
