# Generated by Django 5.2.3 on 2025-07-06 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0002_alter_members_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="member_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="user",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
