# Generated by Django 5.2.3 on 2025-07-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0003_alter_members_member_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="members",
            name="password",
        ),
    ]
